# This script is an experiment to estimation power generated by a cyclist on a Elite suprt chrono power fluid hometrainer

# Require:
# pip install python-dateutil

# Lookup table (Power (Watts), Speed (Km/h))
lookup = [
    [0.0, 0.0],
    [100.0, 20.0],
    [200.0, 26.5],
    [300.0, 30.5],
    [400.0, 34.0],
    [500.0, 36.5],
    [600.0, 39.0],
    [700.0, 41.3],
    [800.0, 43.2],
    [900.0, 45.0],
    [1000.0, 46.5]
]

def cvt_speed_pwr(speed):
    speed = float(speed)
    if speed >= 46.5:
        print("Error: You are too powerfull")
        return 1000
    for i in range(len(lookup)):
        if speed >= lookup[i][1] and speed <= lookup[i+1][1]:
            pwr = lookup[i][0] + (lookup[i+1][0]-lookup[i][0])*(speed-lookup[i][1])/(lookup[i+1][1]-lookup[i][1])
            print("%f Km/h -> %f Watts" % (speed, pwr))
            return pwr

cvt_speed_pwr(30)

def trackpoint_to_dic(trackpoint):
    from dateutil.parser import parse
    import time
    dic = {}
    if len(trackpoint.getElementsByTagName('Time')) > 0:
        dic["TimeStamp"] = time.mktime(parse(trackpoint.getElementsByTagName('Time')[0].firstChild.data).timetuple())
    if len(trackpoint.getElementsByTagName('HeartRateBpm')) > 0:
        dic["HeartRate"] = int(trackpoint.getElementsByTagName('HeartRateBpm')[0].childNodes[1].firstChild.data)
    if len(trackpoint.getElementsByTagName('DistanceMeters')) > 0:
        dic["DistanceMeters"] = float(trackpoint.getElementsByTagName('DistanceMeters')[0].firstChild.data)
    if len(trackpoint.getElementsByTagName('ns3:Speed')) > 0:
        dic["Speed"] = float(trackpoint.getElementsByTagName('ns3:Speed')[0].firstChild.data)
    if len(trackpoint.getElementsByTagName('Cadence')) > 0:
        dic["Cadence"] = int(trackpoint.getElementsByTagName('Cadence')[0].firstChild.data)
    return dic

def plot_activity(filename):
    from xml.dom import minidom
    mydoc = minidom.parse(filename)
    trackpoints = mydoc.getElementsByTagName('Trackpoint')
    print(trackpoint_to_dic(trackpoints[200]))

plot_activity("activity_4484818643.tcx")